version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  app:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}:${GITHUB_SHA}  # 실제 Docker 이미지 이름과 태그로 설정
    container_name: spring-boot-app
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8080:8080"
    depends_on:
      - postgres
